# Generated by Django 5.2.17 on 2026-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='damaged_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
