# Generated by Django 5.2.17 on 2026-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_backfill_single_item_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_error',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_lock_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_next_sync_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_provider',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='raw_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='source',
            field=models.CharField(default='local', max_length=24),
        ),
    ]
