# Generated by Django 5.2.17 on 2026-09-13 15:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_backfill_tracking_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='charges_mode',
            field=models.CharField(choices=[('ABSORB', 'Deduct from sale'), ('ADD', 'Add to sale')], default='ABSORB', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('SAME_CITY', 'Same city'), ('SAME_PROVINCE', 'Same province'), ('OUTSIDE_PROVINCE', 'Outside province')], default='OUTSIDE_PROVINCE', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_mode',
            field=models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
