# Generated by Django 5.2.17 on 2026-09-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shipment_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_courier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_courier_cost_basis',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_courier_cost_source',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
