# Generated by Django 5.2.17 on 2026-09-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_dashboard_access(apps, schema_editor):
    """Existing customers must not lose access when the approval gate ships."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(dashboard_access_state="PENDING").update(dashboard_access_state="ACTIVE")


class Migration(migrations.Migration):
    dependencies = [("accounts", "0002_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dashboard_access_state",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Jazzmin approval"),
                    ("ACTIVE", "Dashboard unlocked"),
                    ("SUSPENDED", "Dashboard suspended"),
                ],
                default="ACTIVE",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dashboard_unlocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dashboard_unlocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unlocked_dashboard_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(preserve_existing_dashboard_access, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="dashboard_access_state",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Jazzmin approval"),
                    ("ACTIVE", "Dashboard unlocked"),
                    ("SUSPENDED", "Dashboard suspended"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
