# Generated by Django 5.2.17 on 2026-09-14 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_sharedcacheentry'),
        ('orders', '0007_shipment_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppWebhook',
            fields=[
                ('fingerprint', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.CharField(max_length=80, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('marketing_enabled', models.BooleanField(default=False)),
                ('events', models.JSONField(default=list)),
                ('templates', models.JSONField(default=dict)),
                ('gap_seconds', models.PositiveIntegerField(default=60)),
                ('daily_limit', models.PositiveIntegerField(default=100)),
                ('quiet_start', models.PositiveSmallIntegerField(default=20)),
                ('quiet_end', models.PositiveSmallIntegerField(default=9)),
                ('session_status', models.CharField(default='NOT_CONNECTED', max_length=40)),
                ('last_error', models.CharField(blank=True, max_length=250)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('product_snapshot', models.JSONField(default=list)),
                ('scheduled_at', models.DateTimeField()),
                ('state', models.CharField(default='DRAFT', max_length=16)),
                ('audience_count', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('transactional', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('opted_out', models.BooleanField(default=False)),
                ('consent_note', models.CharField(blank=True, max_length=250)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=16)),
                ('event', models.CharField(blank=True, max_length=40)),
                ('dedup_key', models.CharField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('state', models.CharField(db_index=True, default='PENDING', max_length=16)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField()),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=250)),
                ('error', models.CharField(blank=True, max_length=250)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='messaging.whatsappaccount')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='messaging.whatsappcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='messaging.whatsappcontact')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='whatsappcontact',
            constraint=models.UniqueConstraint(fields=('workspace', 'phone'), name='unique_wa_contact'),
        ),
    ]
