# Generated by Django 5.2.17 on 2026-09-14 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sharedcacheentry'),
        ('messaging', '0002_default_customer_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaign',
            name='audience_mode',
            field=models.CharField(default='ALL', max_length=16),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='kind',
            field=models.CharField(default='PRODUCT', max_length=16),
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='recipient_ids',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='WhatsAppMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000)),
                ('filename', models.CharField(max_length=150)),
                ('mimetype', models.CharField(max_length=80)),
                ('size', models.PositiveIntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='messaging.whatsappmedia'),
        ),
    ]
