# Generated by Django 5.2.17 on 2026-09-15 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_whatsappcampaign_audience_mode_whatsappcampaign_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='ack',
            field=models.SmallIntegerField(default=-2),
        ),
        migrations.CreateModel(
            name='WhatsAppReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=250)),
                ('ack', models.SmallIntegerField(default=-2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.whatsappaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'provider_id'), name='unique_wa_receipt')],
            },
        ),
    ]
