# Generated by Django 5.2.17 on 2026-09-16 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comqora_journal'),
        ('finance', '0001_initial'),
        ('logistics', '0003_courier_city_pricing_courier_extra_fees_and_more'),
        ('orders', '0008_order_actual_courier_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('BANK', 'Bank'), ('WALLET', 'Wallet'), ('CASH', 'Cash')], default='BANK', max_length=10)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_date', models.DateField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettlementImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=200)),
                ('digest', models.CharField(max_length=64)),
                ('source', models.BinaryField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('REVIEW', 'Review'), ('CONFIRMED', 'Confirmed'), ('VOID', 'Void'), ('ERROR', 'Error')], default='QUEUED', max_length=12)),
                ('extracted', models.JSONField(default=dict)),
                ('review', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('error', models.CharField(blank=True, max_length=250)),
                ('processing_token', models.UUIDField(null=True)),
                ('processing_at', models.DateTimeField(null=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('reference_key', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField(null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('confirmed_result', models.JSONField(default=dict)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.courier')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettlementCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basis', models.CharField(max_length=12)),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('previous_basis', models.CharField(blank=True, max_length=12)),
                ('previous_source', models.UUIDField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_updates', to='finance.settlementimport')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=150)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('request_key', models.UUIDField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.bankaccount')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.bankentry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.settlementimport')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='settlementimport',
            constraint=models.UniqueConstraint(fields=('workspace', 'digest'), name='unique_workspace_cpr_file'),
        ),
        migrations.AddConstraint(
            model_name='settlementimport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('workspace', 'courier', 'reference_key'), name='unique_active_cpr_reference'),
        ),
        migrations.AddConstraint(
            model_name='settlementcost',
            constraint=models.UniqueConstraint(fields=('statement', 'order'), name='unique_statement_order_cost'),
        ),
        migrations.AddConstraint(
            model_name='bankentry',
            constraint=models.UniqueConstraint(fields=('workspace', 'request_key'), name='unique_bank_request'),
        ),
    ]
