# Generated by Django 5.2.17 on 2026-09-16 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comqora_journal'),
        ('finance', '0002_bankaccount_settlementimport_settlementcost_and_more'),
        ('logistics', '0003_courier_city_pricing_courier_extra_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature', models.CharField(max_length=64)),
                ('roles', models.JSONField(default=list)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.courier')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.settlementimport')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('workspace', 'courier', 'signature'), name='unique_settlement_layout_mapping')],
            },
        ),
    ]
