# Generated by Django 5.2.17 on 2026-09-16 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comqora_journal'),
        ('finance', '0003_settlementmapping'),
        ('logistics', '0003_courier_city_pricing_courier_extra_fees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='settlementimport',
            name='unique_workspace_cpr_file',
        ),
        migrations.AddField(
            model_name='settlementimport',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='finance.settlementimport'),
        ),
        migrations.AddConstraint(
            model_name='settlementimport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'VOID'), _negated=True), fields=('workspace', 'digest'), name='unique_workspace_cpr_file'),
        ),
    ]
