# Generated by Django 5.2.17 on 2026-09-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_settlementimport_unique_workspace_cpr_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankentry',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.expense'),
        ),
    ]
