# Generated by Django 5.2.17 on 2026-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comqora_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='business_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='workspace',
            name='invoice_footer',
            field=models.CharField(default='Thank you for shopping with us.', max_length=300),
        ),
        migrations.AddField(
            model_name='workspace',
            name='invoice_template',
            field=models.CharField(default='studio', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='logo_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
