# Generated by Django 5.2.17 on 2026-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingWorkerState',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('heartbeat', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='provider',
            field=models.CharField(choices=[('TCS', 'TCS'), ('Leopards', 'Leopards'), ('M&P', 'M&P'), ('Trax', 'Trax'), ('Daewoo', 'Daewoo'), ('Dastaq Logistic', 'Dastaq Logistic'), ('AHL', 'AHL'), ('PostEx', 'PostEx'), ('Others', 'Others')], default='Others', max_length=24),
        ),
    ]
