# Generated by Django 5.2.17 on 2026-09-13 15:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_trackingworkerstate_courier_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='city_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='extra_fees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='courier',
            name='outside_province_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='courier',
            name='provincial_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='same_city_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='courier',
            name='same_province_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='courier',
            name='base_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
