# Generated by Django 5.2.17 on 2026-09-12 18:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('Meta', 'Meta'), ('Google', 'Google'), ('TikTok', 'TikTok'), ('Other', 'Other')], default='Meta', max_length=30)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocated', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ad_allocations', to='orders.order')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='marketing.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
