# Generated by Django 5.2.17 on 2026-09-18 08:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_workspace_print_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fazita', max_length=80)),
                ('key_environment_variable', models.CharField(default='FAZITA_API_KEY', help_text='Put the secret in Backend/.env or Railway Variables. Only its variable name is stored here.', max_length=80, validators=[django.core.validators.RegexValidator('^FAZITA_[A-Z0-9_]+$', 'Use a FAZITA_ environment variable name, not the secret itself.')])),
                ('enabled', models.BooleanField(default=True)),
                ('daily_workspace_turn_limit', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
            ],
            options={
                'verbose_name': 'AI provider connection',
            },
        ),
        migrations.CreateModel(
            name='AssistantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name shown in the assistant.', max_length=100)),
                ('model_id', models.CharField(help_text="Exact model ID from your Fazita group's Use Key screen.", max_length=150)),
                ('protocol', models.CharField(choices=[('responses', 'Responses · /v1/responses'), ('chat', 'Chat completions · /v1/chat/completions'), ('messages', 'Anthropic messages · /v1/messages')], default='responses', max_length=16)),
                ('enabled', models.BooleanField(default=False, help_text='Enable after checking your key/group supports this model and tool calling.')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lowest number is the default model.')),
                ('max_output_tokens', models.PositiveIntegerField(default=2048, validators=[django.core.validators.MinValueValidator(512), django.core.validators.MaxValueValidator(4096)])),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='assistant.connection')),
            ],
            options={
                'ordering': ['priority', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='New conversation', max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_key', models.UUIDField(default=uuid.uuid4)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='RUNNING', max_length=12)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('sources', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('usage', models.JSONField(default=dict)),
                ('finished_at', models.DateTimeField(null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='assistant.conversation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assistant.assistantmodel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=12)),
                ('result', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='assistant.turn')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='assistantmodel',
            constraint=models.UniqueConstraint(fields=('connection', 'model_id', 'protocol'), name='unique_assistant_model'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(fields=('conversation', 'request_key'), name='unique_assistant_turn_request'),
        ),
    ]
