# Generated by Django 5.2.17 on 2026-09-18 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_default_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='encrypted_api_key',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='key_environment_variable',
            field=models.CharField(default='FAZITA_API_KEY', help_text='Optional fallback when no API key is saved above. Most admins can leave this unchanged.', max_length=80, validators=[django.core.validators.RegexValidator('^FAZITA_[A-Z0-9_]+$', 'Use a FAZITA_ environment variable name, not the secret itself.')]),
        ),
    ]
