# Generated by Django 5.2.17 on 2026-09-19 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_connection_encrypted_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmodel',
            name='max_output_tokens',
            field=models.PositiveIntegerField(default=8192, help_text='Per model request, including reasoning tokens where supported. Higher limits can increase cost and latency. Must also be supported by your provider/model.', validators=[django.core.validators.MinValueValidator(512), django.core.validators.MaxValueValidator(32768)]),
        ),
    ]
