# Generated by Django 5.2.17 on 2026-09-19 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_assistantmodel_max_output_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmodel',
            name='max_output_tokens',
            field=models.PositiveIntegerField(blank=True, default=8192, help_text='Leave blank for provider default (Responses/Chat): no app token cap is sent; provider limits still apply. Messages requires a number. Higher budgets can increase cost and latency.', null=True, validators=[django.core.validators.MinValueValidator(512), django.core.validators.MaxValueValidator(32768)]),
        ),
    ]
