# Generated by Django 5.2.17 on 2026-09-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_alter_assistantmodel_max_output_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='processing_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=12),
        ),
    ]
