# Generated by Django 5.2.17 on 2026-09-12 18:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('meter', 'Meter'), ('gram', 'Gram')], default='piece', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=60)),
                ('category', models.CharField(default='General', max_length=80)),
                ('variant', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('image_url', models.URLField(blank=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80)),
                ('purchased_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_at', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['received_at', 'created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('workspace', 'sku'), name='unique_workspace_sku'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('remaining_quantity'))), name='reserved_within_stock'),
        ),
    ]
