# Generated by Django 5.2.17 on 2026-09-13 15:11

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0002_sharedcacheentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='extra_costs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='import_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='purchase_mode',
            field=models.CharField(choices=[('UNIT', 'Per unit'), ('TOTAL', 'Batch total')], default='UNIT', max_length=8),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), name='unique_workspace_category'),
        ),
    ]
